name: Sync to Hugging Face hub
on:
  push:
    branches:
      - develop
      - main
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-large-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760 # this is 10MB
  sync-to-hub:
    needs: [check-large-files]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Get branch name
        id: get-branch-name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://mlops-pltf:$HF_TOKEN@huggingface.co/spaces/mlops-pltf/hfagnt-first-smolagent-app ${{ steps.get-branch-name.outputs.BRANCH_NAME }}